name: CI/CD Pipeline

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Directory Contents
        run: ls -R 
        shell: bash
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn -f SoftwareTechLab/LibraryProject/pom.xml clean install

      - name: Run Tests
        run: mvn -f SoftwareTechLab/LibraryProject/pom.xml test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Package Application
        run: mvn -f SoftwareTechLab/LibraryProject/pom.xml clean package

