name: CI/CD Pipeline

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current Working Directory
        run: pwd
        
      - name: Print Directory Contents
        run: ls -R 
        shell: bash   
        
      - name: Change Working Directory
        run: cd ../
        
      - name: Print Current Working Directory
        run: pwd
        
      - name: Print Directory Contents
        run: ls -R 
        shell: bash   
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package -f SoftwareTechLab/LibraryProject/pom.xml clean 
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


