name: CI/CD Pipeline

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        env:
          NODE_VERSION: '20'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
  
  deploy:
    runs-on: ${{ github.event.inputs.chosen-os }}
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Package Application
        run: mvn clean package

