name: CI/CD Pipeline

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - Ubuntu
          - macOS
          - Windows

jobs:
  build:
    runs-on: ${{ github.event.inputs.chosen-os }}

    steps:
      - name: Debug Info
        run: |
          echo "Chosen OS: ${{ github.event.inputs.chosen-os }}"
          env  # Print all environment variables for debugging
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
  
  deploy:
    runs-on: ${{ github.event.inputs.chosen-os }}
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Package Application
        run: mvn clean package

